### ISSUE TITLE
gene_profile plot x-axis labels are offset and sometimes missing

### ISSUE THREAD

**Issue by tstannius** [perslab/CELLEX#1]
When the dataframe contains 20-40 cell-types, labels are offset to the left.
When the dataframe contains <= 20 cell-types, the labels are shifted one place to the left and the leftmost one disappears.

This may be an issue with plotnine.

### Example: dataframe with 21 cell-types
Labels are offset, but match the plot.
![21celltypes](https://user-images.githubusercontent.com/23248552/62832350-e9e20f00-bc2c-11e9-94a3-e477bd872a70.png)

### Example: dataframe with 20 cell-types
Labels are offset and one label is missing (on the left)

![20celltypes](https://user-images.githubusercontent.com/23248552/62832354-ee0e2c80-bc2c-11e9-8c65-ba9dec946d53.png)

**Comment by Satannius** [comment]
Floating labels (unreleased) obscure the chart.
X-axis are offset.

**Example**
![displaced_labels](https://user-images.githubusercontent.com/23248552/73974975-afc8a000-4925-11ea-97ad-f9208b271982.png)

**Comment by tstannius** [comment]
Closing as this clarification will become obsolete with v2 which will not include plots.
