### ISSUE TITLE
Error in READ.ME

### ISSUE THREAD

**Issue by liubovpashkova** [perslab/CELLEX#10]
A wrong parameter name in the ESObject constructor:

## Create ESObject and compute ESmu

```python
eso = cellex.ESObject(df=data, annotation=metadata, verbose=True)
```

Here we must have 'data' as the first parameter name instead of 'df': 

```python
eso = cellex.ESObject(data=data, annotation=metadata, verbose=True)
```

**Comment by Satannius** [comment]
Thank you for pointing this out - I fixed it in the develop branch.
Changes will be merged into the master branch once #8  has been solved.
Until then you can clone the develop branch and install using `pip install -e .`
