### ISSUE TITLE
Syntax Error in det.py file

### ISSUE THREAD

**Issue by vidalmarroyo** [perslab/CELLEX#18]
Hello!

There seems to be a syntax error issue in the 'det.py' file under cellex/metrics/. I am trying to install and run cellex, but whenever I try to install cellex it always gives me an 'invalid syntax' error at the following line:

```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/vidalarroyo/CELLECT/CELLEX/setup.py", line 5, in <module>
        from cellex import __author__, __email__
      File "cellex/__init__.py", line 17, in <module>
        from . import metrics
      File "cellex/metrics/__init__.py", line 1, in <module>
        from .det import det
      File "cellex/metrics/det.py", line 9
        def _det(mean: pd.DataFrame, var: pd.DataFrame, n_cells: pd.DataFrame, verbose: bool=False):
                     ^
    SyntaxError: invalid syntax
```

**Comment by tstannius** [comment]
Hi!

Could you add the command that resulted in this error?
Thanks in advance.

**Comment by vmarroyo** [comment]
Yes! The command was 'pip install -e'. I was going through the walkthrough on https://github.com/perslab/CELLEX , using Option B on the setup

**Comment by tstannius** [comment]
How odd. I am having trouble reproducing the error. Does my approach differ to yours?

![install_cellex_option_b](https://user-images.githubusercontent.com/23248552/78793821-3c89eb80-79b3-11ea-80bf-1a460bceee56.gif)

**Comment by vmarroyo** [comment]
Hmm, I gave both a try (both the way you did it in the gif and installing cellex via pip) and neither worked :/ i'm thinking it may be the version of python my terminal is set up with.... what version is used?

**Comment by tstannius** [comment]
Bummer, but we'll just have to try something else then :-) and thank you for your patience in that regard.

CELLEX has been developed for use in a Python 3 environment.
I use conda environments (miniconda3) to manage the installation. Here's what I do step by step:

```bash
# create environment
conda create --no-default-packages --name myenv python

# activate env
source activate myenv

# check python version, should be >3.8
python --version

# install cellex – various dependencies will be installed first
pip install cellex

# test installation in interactive python
python

>>> import cellex
>>>
```

**Comment by vmarroyo** [comment]
Yes! And thank you so much for your help with all of this. I will be re-trying this tomorrow on a cluster environment, and this will help me tons. I will keep you posted!

**Comment by tstannius** [comment]
Hi again Vidal,

Have you made any progress on this issue? 🙂

**Comment by vmarroyo** [comment]
Hey Tobias,

Firstly, thanks for checking in! In short, yes and no - I actually realized that I need to run CELLECT/CELLEX on a cluster, so I am working with my university to get all the necessary software (IE Python 3.8+, Snakemake v. 5.4.5) installed before I continue some of this.

Once I do, I will be sure to reach out once I am able to continue the tutorial :) thanks for checking in!

Best,

Vidal Arroyo
MSc by Research in Statistics
University College, Oxford
https://www.linkedin.com/in/vidalarroyo

**Comment by vidalmarroyo** [comment]
Hello Tobias,

Just following up, what are the bare minimum requirements in terms of software (IE python, snakemake, etc.) and versions to run CELLECT/CELLEX? We are working with our clustering management team to download any necessary software, so I want to make sure  have all that up front :)

**Comment by tstannius** [comment]
Hi again Vidal!

CELLECT/CELLEX were developed on a server, so I'm not entirely sure how it will behave on a cluster – nevertheless ...
We have sought to make both CELLECT and CELLEX self-contained. Ideally the environment manager (conda) and package manager (pip) should take care of everything, i.e. installing dependencies. The workflow is essentially: 1) create a virtual environment, 2) install the needed dependencies in the environment, 3) run the analysis. Therefore I would recommend that you start off with the most recent version of `conda`, `pip` and `python3`.

For CELLEX
* Get conda
* Create a new python3 environment and activate it
* Run `pip install cellex`, which will also install the required dependencies.

For CELLECT
* Get conda
* Follow [this](https://github.com/perslab/CELLECT/wiki/CELLECT-LDSC-Tutorial) tutorial.
* Step 1: The principle is almost the same as for CELLEX. To run the GWAS munge workflow, you create an environment (including all dependencies) as specified in [this](https://github.com/pascaltimshel/ldsc/blob/d869cfd1e9fe1abc03b65c00b8a672bd530d0617/environment_munge_ldsc.yml) settings file.
* Step 2: Run CELLEX
* Step 3: Once again, create a new environment with snakemake (`pip install snakemake` for the most recent version).

If this doesn't work out, I'll try and get an expert opinion from the CELLECT devs or our server admin :-)

**Comment by vidalmarroyo** [comment]
Tobias - thank you so much for all of this info! I am also sorry that this has taken a lot of effort and time on your end without much output on our end yet. I am realizing that a lot of these issues are actually driven by my current cluster access situation, so I am going to work within my group to solve those. I will reach out again if I think there is a larger issue - but for the time being I'm set :) thank you and take care!

**Comment by tstannius** [comment]
Hi! Thanks for following up and don't worry – I'm happy to help :-)
Don't hesitate to file a new issue if needed. Take care!
