### ISSUE TITLE
Update parameter name in CELLEX wiki

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLEX#19]
the [CELLEX workflow wiki page](https://github.com/perslab/CELLEX/wiki/CELLEX-workflow) gives the following example of running `ESObject`: 

`cellex.ESObject(df=data, annotation=metadata, normalize=False, verbose=True)`

however the name of the first argument should be 'data'

**Comment by tstannius** [comment]
Fixed, thanks Jon :-)
