### ISSUE TITLE
Improve mapping documentation

### ISSUE THREAD

**Issue by tstannius** [perslab/CELLEX#20]
# Problem
1. The documentation is not clear on which genome build(s) are being used for mapping.
2. Furthermore, the resources used from mapping are from different builds.

# Solution
1. Update documentation of mapping functions.
2. Update the mapping files to be consistent.

**Comment by pascaltimshel** [comment]
**genome builds**: CELLEX gene ID and gene ortholog mapping do not have to be specific to one genome build, as long as the mapping covers as many as possible of the CELLECT gene universe. E.g. mapping ENSG to HGNC is not really dependent on the genome build.

**documentation+ consistency of mapping**: added in this commit to develop https://github.com/perslab/CELLEX/commit/80a34d205f384d891891bd4ec985ad631aa8bd0d

**Comment by pascaltimshel** [comment]
@tstannius : will you update the wiki to reference to the gene mapping functions?

**Comment by tstannius** [comment]
Done 👍
