### ISSUE TITLE
gene mapping function: from symbol to ensembl

### ISSUE THREAD

**Issue by pascaltimshel** [perslab/CELLEX#26]
**Problem**
Many scRNA-seq data sets come with human gene symbols. We should make it easier for users to map to Ensembl IDs, since this is used in CELLECT.

**Solution**
Write function to map from human ens to symbol.

Additionally, _consider_ updating mapping function names for more consistency:
(NEW: ens_human_symbol_to_ens --> human_symbol_to_human_ens)
ens_human_to_symbol --> human_ens_to_human_symbol
ens_mouse_to_ens_human --> mouse_ens_to_human_ens
mgi_mouse_to_ens_mouse --> mouse_symbol_to_mouse_ens

The appropriate file to make the mapping is attached (which allows for mapping genes with 'version numbers' to the appropriate Ensembl ID): 
[GRCh38.ens_v90.gene_name_version2ensembl.txt.gz](https://github.com/perslab/CELLEX/files/4715827/GRCh38.ens_v90.gene_name_version2ensembl.txt.gz)

**Comment by tstannius** [comment]
Hi P,

I've got a prototype ready, but while we're at it, I would like to address #20 - could you make a GRCh38 map for mouse_ens_to_human_ens (and human_ens_to_mouse_ens, if you think it's relevant)?

Also, for future reference, could you describe how the mapping files are made?

**Comment by pascaltimshel** [comment]
Done: https://github.com/perslab/CELLEX/commit/80a34d205f384d891891bd4ec985ad631aa8bd0d .

**Comment by tstannius** [comment]
Mapping utils updated and added human symbol to human ensemble in https://github.com/perslab/CELLEX/commit/4ccd65af6823f775a31a6c3dbaf52beb08120211
