### ISSUE TITLE
eso.results[“esmu”] data.frame lacks index column name 

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLEX#27]
## Description: 
* the output of `eso.compute()`, `eso.results[“esmu”]`, lacks index column name (should be 'gene')

**Comment by tstannius** [comment]
Some context:
CELLECT requires that index column name is "gene".

Index column name  added in https://github.com/perslab/CELLEX/commit/f1b07a588ccc5e6ca900aa15d9b7f619ccc658ff
