### ISSUE TITLE
[FEATURE REQUEST]: Work with large datasets

### ISSUE THREAD

**Issue by brianlamx** [perslab/CELLEX#36]
Hi there,

I'm trying to run CELLEX to create the specificity score for downstream CELLECT analysis.  

Our current dataset has ~500K cells and exporting it into dense matrix looks to be prohibitive, plus we may not have a system that has enough memory to run the software.

Do you have any suggestion how we can do this, would bootstrapping work?  

Or do you have a version that makes use of sparse matrices natively? 

Many thanks
Brian

**Comment by tstannius** [comment]
Hi Brian,

Thanks for your patience.

My advice would be to try the following:
1. Ensure that your input data is loaded as float32 precision. This should reduce the memory footprint.
2. If your research question permits, filter out genes that are not of interest. To my understanding, CELLECT only uses the protein coding genes, so you could try and reduce to these, but I would recommend you check with the CELLECT devs.
3. Subsample cells from the cell groups of interest.

We are working on a version 2, which addresses the performance issues by e.g. using sparse matrices, but I expect it will not be ready for a few months.

I hope this answers your question and helps you to move on with your work.

Best,
Tobias
