### ISSUE TITLE
[BUG]: eso.compute error. 

### ISSUE THREAD

**Issue by myylee** [perslab/CELLEX#37]
Hi there, 

Thanks for the great package. 

While running the eso.compute(), I encountered an error like this. 
<img width="1010" alt="Screen Shot 2024-04-26 at 11 20 12 AM" src="https://github.com/perslab/CELLEX/assets/66084077/4c63e657-6fb7-4128-b080-a7eebdef8c4a">

I did install all the requirements as in the requirement.txt file, which was also suggested in previous issues. 

I was able to run CELLEX with the mousebrain_vascular_cells example, just not my dataset. 

I'd greatly appreciate any thought on what is causing the error and how might one solve it. 

Thanks! 

Best regards,
Michelle

**Comment by myylee** [comment]
I think part of the reason is that after eso = cellex.ESObject(data=data_fil, annotation=md_format_fil, verbose=True), my eso.summary_data.variance has a shape of (0,8). But I don't know why the variance matrix was not calculated on my dataset.

**Comment by myylee** [comment]
Nvm, I solved it. It was because my panda dataframe is a sparse instead of dense.

**Comment by tstannius** [comment]
Hi myylee

Glad to hear that you solved the issue 😄 

Yes, most modern sc datasets use sparse data now, which CELLEX was not written to work with.

Best,
Tobi
