### ISSUE TITLE
quick start tutorial: AttributeError: 'ESObject' object has no attribute 'save'

### ISSUE THREAD

**Issue by JonThom** [perslab/CELLEX#7]
# Tutorial

## Code entered

`eso.save(verbose=True)`

## expected behaviour

save the results to disk

## actual behaviour
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-dc489ac63987> in <module>
----> 1 eso.save(verbose=True)

AttributeError: 'ESObject' object has no attribute 'save'`

**Comment by JonThom** [comment]
(having installed cellex through pip)

**Comment by JonThom** [comment]
Suggested fix: in quick start tutorial replace `eso.save` by `eso.save_as_csv`

**Comment by Satannius** [comment]
Fixed by @pvtodorov in #6
